//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.D2UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="D2UserServiceReference.ID2User", CallbackContract=typeof(ConsoleClient.D2UserServiceReference.ID2UserCallback))]
    public interface ID2User {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID2User/GetD2UserPassword", ReplyAction="http://tempuri.org/ID2User/GetD2UserPasswordResponse")]
        byte[] GetD2UserPassword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID2User/SubscribeOnPasswordChange", ReplyAction="http://tempuri.org/ID2User/SubscribeOnPasswordChangeResponse")]
        void SubscribeOnPasswordChange();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ID2User/UnsubscribeFromPasswordChange", ReplyAction="http://tempuri.org/ID2User/UnsubscribeFromPasswordChangeResponse")]
        void UnsubscribeFromPasswordChange();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ID2UserCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ID2User/NotifyPasswordChange")]
        void NotifyPasswordChange(byte[] newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ID2UserChannel : ConsoleClient.D2UserServiceReference.ID2User, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class D2UserClient : System.ServiceModel.DuplexClientBase<ConsoleClient.D2UserServiceReference.ID2User>, ConsoleClient.D2UserServiceReference.ID2User {
        
        public D2UserClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public D2UserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public D2UserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public D2UserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public D2UserClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public byte[] GetD2UserPassword() {
            return base.Channel.GetD2UserPassword();
        }
        
        public void SubscribeOnPasswordChange() {
            base.Channel.SubscribeOnPasswordChange();
        }
        
        public void UnsubscribeFromPasswordChange() {
            base.Channel.UnsubscribeFromPasswordChange();
        }
    }
}
